name: Raju_Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs: 
  raju_bhaiyy_ki_pilpeline:
    runs-on: ubuntu-latest

    steps:
      - name: Bhaiyyaji pahle checkout krona
        uses: actions/checkout@v4

      - name: Bhaiyyaji pahle login karo na
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: bhaiyya ji tf download kar na 
        uses: hashicorp/setup-terraform@v2
      
      - name: bhaiyya ji init karo na 
        run: terraform init
     
      - name: bhaiyya ji init & apply karo na 
        run: |
         terraform plan
         terraform  apply --auto-approve
         terraform  destroy
         
